# Generated by Django 3.1.3 on 2020-11-24 09:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 11, 24, 14, 57, 30, 33469)),
        ),
        migrations.AddField(
            model_name='service',
            name='lead_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='service',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
