# Generated by Django 3.1.3 on 2020-11-24 09:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0003_auto_20201124_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 11, 24, 9, 59, 23, 632625, tzinfo=utc)),
        ),
    ]
