# Generated by Django 3.1.3 on 2020-11-24 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0008_auto_20201124_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='discount',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=11),
        ),
    ]
