# Generated by Django 3.1.3 on 2020-11-24 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0009_auto_20201124_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='picture',
            field=models.TextField(default='../static/images'),
        ),
        migrations.AddField(
            model_name='user',
            name='qualification',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
