# Generated by Django 3.1.3 on 2020-11-24 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0012_user_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(blank=True, upload_to='static/images'),
        ),
    ]
