# Generated by Django 3.1.3 on 2020-11-25 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0013_auto_20201124_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=11)),
                ('discount', models.IntegerField(blank=True, default=0)),
                ('qualification', models.IntegerField(blank=True, default=0)),
                ('picture', models.ImageField(blank=True, upload_to='static/images')),
                ('description', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_id', to='courseapp.employee'),
        ),
        migrations.AlterField(
            model_name='order',
            name='master_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_id', to='courseapp.employee'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
