# Generated by Django 3.1.3 on 2020-11-25 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0014_auto_20201125_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='privilege',
            field=models.CharField(default='', max_length=10),
        ),
    ]
