# Generated by Django 3.1.3 on 2020-11-25 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0015_employee_privilege'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='password',
            field=models.CharField(default='', max_length=30),
        ),
    ]
