# Generated by Django 3.1.3 on 2020-11-25 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0016_employee_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='service',
        ),
        migrations.AddField(
            model_name='order',
            name='service',
            field=models.ManyToManyField(to='courseapp.Service'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='privilege',
            field=models.CharField(default='customer', max_length=10),
        ),
    ]
