# Generated by Django 3.1.3 on 2020-11-25 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0018_auto_20201125_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='service',
            field=models.ManyToManyField(related_name='service_rel', to='courseapp.Service'),
        ),
    ]
